### ISSUE TITLE
Cloning error

### ISSUE THREAD

**Issue by crisp2u** [DanielThomas/oh-your-dotfiles#23]
This fails https://github.com/DanielThomas/oh-your-dotfiles/blob/89a7ba9335370345c724530129fdeda6ae69b522/lib/git.zsh#L14 because it cannot switch to an unexisting directory (before clone). 

I would do a pull request but i messed up my fork

**Comment by DanielThomas** [comment]
Oh, nice catch @crisp2u. Let me fix that
