### ISSUE TITLE
Lack of support for symlink directories?

### ISSUE THREAD

**Issue by weksler** [DanielThomas/oh-your-dotfiles#24]
The `README` states:
"... If a directory the files within will be symlinked relatively, for instance `config.symlink/mytool/myconfig` will be linked as `$HOME/.config/mytool/myconfig` ... "

I recently observed this behavior to be broken, and inspecting the code, it seems like the culprit is that the symlink code [uses `dotfiles_find` to find candidates to be symlinked](https://github.com/DanielThomas/oh-your-dotfiles/blob/c1782542088850440cfc848859a335c6a96957bd/lib/install.zsh#L144), but `dotfiles_find` [uses a `-type f` filter to `find`](https://github.com/DanielThomas/oh-your-dotfiles/blob/c1782542088850440cfc848859a335c6a96957bd/lib/dotfiles.zsh#L36), which means it will only ever find files, and never directories. In a quick test I did locally, removing the `-type f` filter made things start work for directories as well.

So the readme seems to be inconsistent with the implementation.

I hesitate to send a PR because I don't know what the implications of simply removing that `-type f` filter would be, seeing as `dotfiles_find` is used all over the place.

**Comment by lorin** [comment]
I just hit the same issue.

**Comment by DanielThomas** [comment]
This is fixed, I completely missed this was broken.
